### ISSUE TITLE
Develop a Client Certificate to Kerberos solution

### ISSUE THREAD

**Issue by teamaccessonline** [teamaccessonline/library#22]
**What is solution trying to demonstrate?**
A solution guide that demonstrates ODCA, OCSP, and LDAP Query to Kerberos SSO

**Describe alternatives you've considered**
none

**Additional context**

**Comment by yahshun** [comment]
Assigned Solution6 Folder

**Comment by yahshun** [comment]
Policy and postman Collection Commited to Master
